sudo: required
dist: trusty

language: haxe

os:
  - linux
  
haxe:
  - "3.4.0"
    
install:
  - haxelib install travix
  - haxelib run travix install
  - haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs
  - curl -s -L --retry 3 'http://nekovm.org/_media/neko-2.1.0-linux64.tar.gz' | tar -C ${HOME}/haxe/neko -x -z --strip-components=1 -f -

script:
  - haxelib run travix node
  - haxe all.hxml
  - node bin/haxelibshim.js
