sudo: required
dist: trusty

language: node_js
node_js: 6

os:
  - linux
  #- osx
    
install:

  - mkdir -p ${HOME}/haxe/neko
  - mkdir -p ${HOME}/haxe/haxelib
  - mkdir -p ${HOME}/haxe/versions/4.0.0-rc.2

  - echo '{"version":"4.0.0-rc.2","resolveLibs":"mixed"}' > ${HOME}/haxe/.haxerc
  
  - curl -s -L --retry 3 'http://nekovm.org/_media/neko-2.1.0-linux64.tar.gz' | tar -C ${HOME}/haxe/neko -x -z --strip-components=1 -f -
  - curl -s -L --retry 3 'http://haxe.org/website-content/downloads/4.0.0-rc.2/downloads/haxe-4.0.0-rc.2-linux64.tar.gz' | tar -C ${HOME}/haxe/versions/4.0.0-rc.2 -x -z --strip-components=1 -f -

  - export HAXE_STD_PATH=${HOME}/haxe/versions/4.0.0-rc.2/std
  - ${HOME}/haxe/versions/4.0.0-rc.2/haxe all.hxml
  - unset HAXE_STD_PATH
  
  - npm install . -g
  - neko -version
  - haxelib version
  - haxelib install travix
  - haxelib git ansi https://github.com/kevinresol/ansi
  - haxelib run travix install
  - haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs

script:
  - haxelib run travix node
  - haxe all.hxml
  - neko -version
